version: '3'

services:
  react:
    build: ./react
    restart: always
    volumes:
      - ./react:/app
      - react-deps:/app/node_modules
    ports:
      - 6006:6006

  paybutton:
    build: ./paybutton
    restart: always
    volumes:
      - ./paybutton:/app
      - ./react:/react
      - paybutton-deps:/app/node_modules

volumes:
  react-deps:
  paybutton-deps:
