name: Run tests
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install base dependencies
        run: |
          yarn
          cd react
          yarn

      - name: Run react unit tests
        run: |
          cd react
          yarn test
