name: Setup, test and build

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install root dependencies
        run: yarn

      - name: Install react dependencies
        run: |
          cd react
          yarn

      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: deps
          path: |
            ./node_modules
            ./react/node_modules
            ./react/yarn.lock
            ./react/lib/paybutton-config.json

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: deps

      - name: Run react unit tests
        run: |
          yarn test

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: deps

      - name: Build
        run: yarn build

      - name: Check TS declaration files
        run: |
          [[ -f react/dist/index.d.ts ]]

